container:
  secretsFrom:
    - subscription
resources:
  limits: null
  requests: null
health:
  liveliness:
    path: '/q/health/live'
  readiness:
    path: '/q/health/ready'
  startup:
    path: '/q/health/started'
  port: 8080


