name: Deploy

on:
  push:
    branches:
      - 'master'
      - 'main'
      - 'feat-*'
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  wait:
    name: "Wait for tests"
    runs-on: ubuntu-latest
    steps:
      - name: Wait for tests to succeed
        uses: lewagon/wait-on-check-action@v1.1.2
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          check-name: 'run-tests'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  deploy:
    name: Deploy
    needs:
      - wait
    uses: globalid/.github/.github/workflows/deploy-k8s-quarkus.yml@master
    secrets: inherit
